# Generated by Django 3.2.12 on 2023-07-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_remove_order_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
