# Generated by Django 3.2.12 on 2023-07-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20230710_1635'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='orders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='order_management.order'),
        ),
    ]
