# Generated by Django 4.2.1 on 2023-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
