# Generated by Django 3.2.12 on 2023-07-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_delivery_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
    ]
